apiVersion: v1
kind: Namespace
metadata:
  name: pnp-opsera-gilbert-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnp-opsera-gilbert-deployment
  namespace: pnp-opsera-gilbert-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:831be1c2be619da2f8c9d008b1ad334614fc16ca

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pnp-opsera-gilbert-label
  name: pnp-opsera-gilbert-service
  namespace: pnp-opsera-gilbert-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---